"""added fetch_status

Revision ID: e82ddb50c41b
Revises: fcff5f7334ce
Create Date: 2023-06-16 07:29:33.544671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82ddb50c41b'
down_revision = 'fcff5f7334ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('fetch_status', sa.String(), server_default='completed', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'fetch_status')
    # ### end Alembic commands ###
