"""added latest latest_post_id in feed table

Revision ID: eb30e7665289
Revises: 529ef199c364
Create Date: 2023-06-14 02:58:57.218101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb30e7665289'
down_revision = '529ef199c364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('latest_post_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'latest_post_id')
    # ### end Alembic commands ###
